FROM nginx:stable
WORKDIR /usr/src/app
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/errordocs_default.inc /etc/nginx/errordocs_default.inc
COPY nginx/mime.types /etc/nginx/mime.types
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
